### ISSUE TITLE
alterar títulos

### ISSUE THREAD

**Issue by daniervelin** [leolca/textolivre#25]
https://github.com/leolca/textolivre/blob/fa71ea57cc4db923bd46c30077af976d5e02aa05/issues/2021/v14/n1/26231/article.tex#L23

alterar títulos para:
Crisis socioecológica y comunicación durante la Marea Roja de Chiloé (2016)
Socioecological crisis and communications during the Red Tide of Chiloé (2016)
Crise sócio-ecológica e comunicação durante a Maré Vermelha de Chiloé (2016)

**Comment by leolca** [comment]
@daniervelin  
Estava pensando em adotar a seguinte lógica na ordem dos títulos e resumos:
1. idioma do manuscrito
2. português
3. inglês
Coloquei o português em segundo por ser um periódico brasileiro e, também, acredito que fica mais adequado às normas da revista, uma vez que resumo e palavras-chave são exigidos em português, mas não são exigidos em inglês.

**Comment by daniervelin** [comment]
Está ótima essa ordem, Leo. O problema dos títulos que citei é a escrita da primeira palavra: não é "Crisos" e sim "Crisis". E precisa colocar o nome do evento em maiúculas: Marea Roja de Chiloé (2016).
