### ISSUE TITLE
tabela/quadro

### ISSUE THREAD

**Issue by daniervelin** [leolca/textolivre#27]
https://github.com/leolca/textolivre/blob/fa71ea57cc4db923bd46c30077af976d5e02aa05/issues/2021/v14/n1/26231/article.tex

Temos adotado a regra de usar apenas figura e tabela? Neste artigo aparece no pdf "Cuadro 1". Não é melhor mudar para "Tabla 1"?

**Comment by leolca** [comment]
O padrão do espanhol da Espanha é Cuadro, já do México é Tabla. Trocar para o mexicano trouxe alguns problemas nas citações. Adotei a seguinte solução: https://tex.stackexchange.com/a/378221/37214

**Comment by daniervelin** [comment]
Entendi, Leo! Se o padrão for Cuadro, pode deixar. Estou olhando aqui no arquivo original, mas o autor usa Figura. Não ajudou muito. Se quiser adotar Cuadro, pode mudar. Se for manter tabla, lembre-se de alterar o texto: vi aqui que você mudou para "tabla" na legenda, mas o texto anterior está como "cuadro 1".

**Comment by leolca** [comment]
Trata-se de um problema entre os pacotes cleveref e polyglossia. Uma possível solução seria passar a utilizar o babel ao invés do polyglossia. Ainda vou analisar... por enquanto, vou resolver da forma simples (sem usar o cleveref nas tablas).

Postei o problema no stackexchange:
https://tex.stackexchange.com/questions/582073/how-to-change-the-tablename-and-reflect-also-when-using-cleveref
