### ISSUE TITLE
Na legenda aparece Tabla e no texto Cuadro. Uniformizar.

### ISSUE THREAD

**Issue by daniervelin** [leolca/textolivre#29]
https://github.com/leolca/textolivre/blob/3e26ce0b7b79c3cb246979bb2352532d4fd1a818/issues/2021/v14/n1/26231/article.tex#L457

Na legenda aparece Tabla e no texto Cuadro. Uniformizar.

**Comment by leolca** [comment]
Trata-se de um problema entre os pacotes cleveref e polyglossia. Uma possível solução seria passar a utilizar o babel ao invés do polyglossia. Ainda vou analisar... por enquanto, vou resolver da forma simples (sem usar o cleveref nas tablas).

Postei o problema no stackexchange:
https://tex.stackexchange.com/questions/582073/how-to-change-the-tablename-and-reflect-also-when-using-cleveref
