### ISSUE TITLE
Faltam ORCIDs

### ISSUE THREAD

**Issue by daniervelin** [leolca/textolivre#71]
https://github.com/leolca/textolivre/blob/69540f3e07292ee1bb09ba6dfbcc9a69499ddfa4/issues/2021/v14/n1/25740/article.tex#L51
Favor inserir os ORCIDs dos autores. Estão aqui: https://periodicos.ufmg.br/index.php/textolivre/article/view/25740

**Comment by leolca** [comment]
corrigido
